export { lookup } from './lookup.js'
export { MemoryStorage } from './MemoryStorage.js'
export type { TokenStorage } from './MemoryStorage.js'
export { MagicLinkStrategy as Strategy } from './Strategy.js'
export type { MagicLinkOptions as MagicLinkStrategyOptions } from './Strategy.js'
